/**
 * bp OMP Extension - generated by bp update. Do not edit manually.
 *
 * Provides OMP with:
 *   - session_start: <bp-context> block + role-augmented payload
 *   - before_agent_start: workflow-state custom message
 *   - context: post-compaction reverse-scan re-injection
 *
 * Env bypass: BP_HOOKS=0 or BP_DISABLE_HOOKS=1 disables every handler.
 * Config skip: handlers no-op when bp/config.yaml is missing at ctx.cwd.
 */
import { existsSync, readFileSync } from "node:fs";
import { execSync } from "node:child_process";
import { join } from "node:path";

function isDisabled() {
  return process.env.BP_HOOKS === "0" || process.env.BP_DISABLE_HOOKS === "1";
}

function hasBpConfig(cwd) {
  if (!cwd) return false;
  return existsSync(join(cwd, "bp", "config.yaml"));
}

function detectAgentType(ctx) {
  const tpl = (ctx && ctx.agentTemplate) || "";
  if (tpl.indexOf("planner") !== -1) return "planner";
  if (tpl.indexOf("executor") !== -1) return "executor";
  if (tpl.indexOf("reviewer") !== -1) return "reviewer";
  return "default";
}

function readBpState(cwd) {
  try {
    var out = execSync("bp state --json", { cwd: cwd, encoding: "utf-8", timeout: 3000 });
    var st = JSON.parse(out);
    var lines = [];
    if (st.milestone) lines.push(st.milestone.id + ": " + st.milestone.name + " [" + st.milestone.status + "]");
    if (st.phase) lines.push("  Phase " + st.phase.id + ": " + st.phase.name + " [" + st.phase.status + "]");
    if (st.activeChange) lines.push("  Active: " + st.activeChange.name + " [" + st.activeChange.status + "]");
    if (st.nextAction) lines.push("  Next: " + st.nextAction);
    return lines.join("\n") || "_no state available_";
  } catch {
    return "_no state available_";
  }
}

function readContextRows(bpDir, changeName) {
  if (!changeName) return [];
  const path = join(bpDir, "changes", changeName, "context.jsonl");
  if (!existsSync(path)) return [];
  try {
    const content = readFileSync(path, "utf-8");
    return content.split("\n").filter(function (line) { return line.length > 0; }).map(function (line) {
      try { return JSON.parse(line); } catch { return null; }
    }).filter(function (r) { return r !== null; });
  } catch {
    return [];
  }
}

function readTasksContent(bpDir, changeName) {
  if (!changeName) return "";
  const path = join(bpDir, "changes", changeName, "tasks.md");
  if (!existsSync(path)) return "";
  try {
    return readFileSync(path, "utf-8");
  } catch {
    return "";
  }
}

function generateCompactBlock(cwd) {
  if (!cwd || !hasBpConfig(cwd)) {
    return "<bp-context>\n</bp-context>";
  }
  try {
    var out = execSync("bp context plan --format=compact", { cwd: cwd, encoding: "utf-8", timeout: 5000 });
    return out.trim() || "<bp-context>\n</bp-context>";
  } catch {
    return "<bp-context>\n</bp-context>";
  }
}

function buildMessage(customType, text) {
  return {
    role: "custom",
    customType: customType,
    content: [{ type: "text", text: text }],
    timestamp: Date.now(),
  };
}

export default function bpExtension(api) {
  var _bpStateInjected = false;
  api.on("session_start", function (event, ctx) {
    if (isDisabled()) return;
    var cwd = (ctx && ctx.cwd) || process.cwd();
    if (!hasBpConfig(cwd)) return;
    var agentType = detectAgentType(ctx);
    var activeChangeName = ctx && ctx.activeChangeName;
    var body = generateCompactBlock(cwd);
    var bpDir = join(cwd, "bp");

    if (agentType === "planner") {
      var state = readBpState(cwd);
      body = body + "\n\n## Roadmap State\n" + state;
    } else if (agentType === "executor") {
      var rows = readContextRows(bpDir, activeChangeName);
      var lines = rows.length === 0
        ? ["_no context.jsonl rows_"]
        : rows.map(function (r) {
            var prefix = r.tag === "guard-rail" ? "> GUARD-RAIL: " : "";
            var phase = r.phase ? " [" + r.phase + "]" : "";
            return prefix + "file: " + r.file + phase + " | reason: " + r.reason;
          });
      body = body + "\n\n" + lines.join("\n");
    } else if (agentType === "reviewer") {
      var invRows = readContextRows(bpDir, activeChangeName);
      var invariants = invRows.length === 0
        ? "_no context.jsonl rows_"
        : invRows.map(function (r) { return "- " + r.reason; }).join("\n");
      body = body + "\n\n## Invariants\n" + invariants;
      var tasks = readTasksContent(bpDir, activeChangeName).trim();
      if (tasks) {
        body = body + "\n\n## tasks.md acceptance\n" + tasks;
      }
    }

    api.sendMessage(buildMessage("bp-context", body));
  });

  api.on("before_agent_start", function (event, ctx) {
    if (isDisabled()) return;
    if (_bpStateInjected) return; // once per session (context handler re-injects on compaction)
    _bpStateInjected = true;
    var cwd = (ctx && ctx.cwd) || process.cwd();
    if (!hasBpConfig(cwd)) return;
    var state = readBpState(cwd);
    return {
      message: buildMessage("bp-workflow-state", state),
    };
  });

  api.on("context", function (event, ctx) {
    if (isDisabled()) return;
    var cwd = (ctx && ctx.cwd) || process.cwd();
    if (!hasBpConfig(cwd)) return;
    var lastCompaction = (ctx && ctx.lastCompactionTs) || 0;
    var lastInjection = (ctx && ctx.lastInjectionTs) || 0;
    if (lastCompaction <= lastInjection) return;
    var recent = (ctx && ctx.recentMessages) || [];
    var hasWorkflowState = recent.some(function (m) {
      return m.customType === "bp-workflow-state";
    });
    if (hasWorkflowState) return;
    var state = readBpState(cwd);
    return {
      message: buildMessage("bp-workflow-state", state),
    };
  });
}
