/**
 * bp OMP Hook - artifact-based progress injection.
 * Generated by bp update. Do not edit manually.
 */
import { existsSync } from "node:fs";
import { join } from "node:path";
import { execSync } from "node:child_process";

export default function bpHook(api: { on: (e: string, h: (ev: unknown, ctx: unknown) => unknown) => void; sendMessage: (m: unknown, o?: unknown) => void }): void {
  api.on("session_start", async (_event: unknown, ctx: unknown) => {
    const cwd = (ctx as Record<string, unknown> | null)?.cwd;
    const workDir = typeof cwd === "string" ? cwd : process.cwd();
    if (!existsSync(join(workDir, "bp", "config.yaml"))) return;
    try {
      const output = execSync("bp continue", { cwd: workDir, encoding: "utf-8", timeout: 5000 });
      const lines = output.trim().split("\n").slice(0, 8);
      api.sendMessage({ role: "custom", customType: "bp-session", content: [{ type: "text", text: lines.join("\n") }], timestamp: Date.now() });
    } catch { /* bp CLI not available */ }
  });

  api.on("before_agent_start", async (_event: unknown, ctx: unknown) => {
    const cwd = (ctx as Record<string, unknown> | null)?.cwd;
    const workDir = typeof cwd === "string" ? cwd : process.cwd();
    if (!existsSync(join(workDir, "bp", "config.yaml"))) return;
    try {
      const output = execSync("bp continue", { cwd: workDir, encoding: "utf-8", timeout: 3000 });
      const hint = output.trim().split("\n").find((l: string) => l.startsWith("Next:")) ?? "[bp] Run bp continue for status.";
      const ui = (ctx as Record<string, unknown> | null)?.ui;
      if (ui && typeof ui === "object" && "setStatus" in ui) {
        (ui as { setStatus: (l: string, v: string) => void }).setStatus("bp", hint);
      }
    } catch { /* skip */ }
  });
}
