version: 1
platform:
  - omp
profile: standard
context: ""
workflow:
  commitDocs: true
review: {}
change: {}
git:
  branching: none
  create_tag: true
release:
  template: standard
spec:
  stack: generic
conventions:
  inject: true
models: {}
