/**
 * Row-type interfaces for tables in the canonical SQLite schema.
 *
 * This file is the **source of truth** for downstream phase consumers
 * (profile-crud, resume-import, etc.). The SQL definitions live in
 * src/db/migrations/0001_initial.sql; these TypeScript interfaces
 * mirror them with camelCase field names — callers convert between
 * SQL row format (snake_case columns from db.query(...).all()) and
 * the camelCase business domain via the data layer.
 *
 * Keep these in sync with the migration. Mismatches are caught by the
 * Database.test.ts schema contract test, which asserts the SQL
 * PRAGMA table_info(<table>) columns match the documented names.
 */

/**
 * _schema_version — migration tracking table (1 row per applied migration).
 */
export interface SchemaVersionRow {
  version: number
  appliedAt: string
}

/**
 * profiles — canonical profile row.
 *
 * skills and targetCompanies are persisted as JSON-encoded arrays
 * (TEXT); readers must JSON.parse(row.skills) before use.
 * id is a ULID generated by the profile-crud change.
 */
export interface ProfileRow {
  id: string
  name: string
  resumeText: string
  resumePath: string | null
  targetRole: string
  jd: string
  skills: string[]
  targetCompanies: string[]
  notes: string
  avatarPath: string | null
  createdAt: string
  updatedAt: string
}

/**
 * resume_history — historical snapshots of a profile's resume text.
 *
 * profileId cascades on delete: removing a profile deletes its
 * archived snapshots. archivedAt is the snapshot's archive timestamp.
 */
export interface ResumeHistoryRow {
  id: number
  profileId: string
  resumeText: string
  resumePath: string | null
  archivedAt: string
}

/**
 * Interview lifecycle state. Five values; DB does NOT enforce valid
 * transitions — service layer enforces them per D-1. Stored as TEXT.
 */
export type InterviewStatus = 'created' | 'in_progress' | 'paused' | 'completed' | 'archived'

/**
 * interviews — canonical interview session row (migration 0002).
 *
 * profileId cascades on delete: removing a profile deletes its
 * interviews. scores is a JSON-encoded Record<string, number> of
 * 5-dimension scores (TEXT); readers must JSON.parse(row.scores)
 * before use. id is a ULID generated by the interview-core change.
 */
export interface InterviewRow {
  id: string
  profileId: string
  status: InterviewStatus
  targetRole: string
  interviewerStyle: 'strict' | 'coaching' | 'friendly'
  scores: string | null
  startedAt: string | null
  completedAt: string | null
  pausedAt: string | null
  autoScore: number | null
  createdAt: string
  updatedAt: string
}

/**
 * interview_answers — per-question Q&A and scores (migration 0002).
 *
 * interviewId cascades on delete: removing an interview deletes its
 * answers. scores is a JSON-encoded Record<string, number> of per-
 * question 5-dimension scores (TEXT); readers must JSON.parse before
 * use. phase is an agent-driven tag (defaults to 'general').
 * id is a ULID generated by the interview-core change.
 */
export interface InterviewAnswerRow {
  id: string
  interviewId: string
  questionText: string
  answerText: string
  scores: string | null
  feedback: string
  phase: string
  createdAt: string
}
/**
 * Question category classification. Each question has exactly one
 * category at the persistence boundary; domain consumers decode
 * the stored TEXT back into this union at the service layer.
 */
export type QuestionCategory = 'algorithm' | 'system-design' | 'behavioral'

/**
 * Question difficulty rating. Stored as TEXT; the service layer
 * validates and maps before returning Question objects.
 */
export type QuestionDifficulty = 'easy' | 'medium' | 'hard'

/**
 * questions — canonical question bank row (migration 0003).
 *
 * source and sourceId together form a stable external identity for
 * deduplication across imports. knowledgePoints and testCases are
 * JSON-encoded arrays (TEXT); readers must JSON.parse before use.
 * url is nullable for questions without a web reference.
 * id is a ULID generated by the importing service.
 */
export interface QuestionRow {
  id: string
  source: string
  sourceId: string
  title: string
  content: string
  difficulty: QuestionDifficulty
  category: QuestionCategory
  url: string | null
  referenceAnswer: string
  explanation: string
  knowledgePoints: string
  testCases: string
  createdAt: string
  updatedAt: string
}

/**
 * tags — normalized tag names (migration 0003).
 *
 * name is unique so shared tags across questions are represented
 * once. id is a ULID generated by the importing service.
 */
export interface TagRow {
  id: string
  name: string
}

/**
 * question_tags — many-to-many link table (migration 0003).
 *
 * The composite primary key prevents duplicate associations. Deleting
 * a question cascades to its links; referenced tags cannot be deleted.
 */
export interface QuestionTagRow {
  questionId: string
  tagId: string
}
