/**
 * Row-type interfaces for tables in the canonical SQLite schema.
 *
 * This file is the **source of truth** for downstream phase consumers
 * (profile-crud, resume-import, etc.). The SQL definitions live in
 * src/db/migrations/0001_initial.sql; these TypeScript interfaces
 * mirror them with camelCase field names — callers convert between
 * SQL row format (snake_case columns from db.query(...).all()) and
 * the camelCase business domain via the data layer.
 *
 * Keep these in sync with the migration. Mismatches are caught by the
 * Database.test.ts schema contract test, which asserts the SQL
 * PRAGMA table_info(<table>) columns match the documented names.
 */

/**
 * _schema_version — migration tracking table (1 row per applied migration).
 */
export interface SchemaVersionRow {
  version: number
  appliedAt: string
}

/**
 * profiles — canonical profile row.
 *
 * skills and targetCompanies are persisted as JSON-encoded arrays
 * (TEXT); readers must JSON.parse(row.skills) before use.
 * id is a ULID generated by the profile-crud change.
 */
export interface ProfileRow {
  id: string
  name: string
  resumeText: string
  resumePath: string | null
  targetRole: string
  jd: string
  skills: string[]
  targetCompanies: string[]
  notes: string
  avatarPath: string | null
  createdAt: string
  updatedAt: string
}

/**
 * resume_history — historical snapshots of a profile's resume text.
 *
 * profileId cascades on delete: removing a profile deletes its
 * archived snapshots. archivedAt is the snapshot's archive timestamp.
 */
export interface ResumeHistoryRow {
  id: number
  profileId: string
  resumeText: string
  resumePath: string | null
  archivedAt: string
}
